<a href="https://colab.research.google.com/github/GeokLiu/WIA1007-tutorial/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array of size 2 x 2

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [ ]:
b=np.random.random((3,4))
print(b)

[[0.75709421 0.32851696 0.90833919 0.52408975]
 [0.93569038 0.8742035  0.46381315 0.36993846]
 [0.46903118 0.85468439 0.77732754 0.90007295]]


3. Create a numpy array of ones and a numpy array of zeroes

In [ ]:
c=np.ones((2,2))
d=np.zeros((3,6))
print(c)
print(d)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [ ]:
d=np.random.random((6,3))
e=np.transpose(d)
print(d)
print(e)

[[0.73579007 0.47251741 0.84929039]
 [0.7048962  0.59442767 0.56692643]
 [0.89973508 0.18403    0.09900464]
 [0.03572896 0.33470035 0.27386422]
 [0.09927476 0.35919188 0.55629967]
 [0.64649775 0.06183462 0.9332847 ]]
[[0.73579007 0.7048962  0.89973508 0.03572896 0.09927476 0.64649775]
 [0.47251741 0.59442767 0.18403    0.33470035 0.35919188 0.06183462]
 [0.84929039 0.56692643 0.09900464 0.27386422 0.55629967 0.9332847 ]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [ ]:
f=np.random.random((2,3))
g=np.random.random((3,4))
h=np.dot(f,g)
print(f)
print(g)
print(h)

[[0.48032767 0.25583612 0.52646997]
 [0.45553201 0.48815857 0.50565733]]
[[0.56912576 0.28385064 0.95678882 0.80873223]
 [0.38092744 0.01508633 0.78004721 0.1163418 ]
 [0.82843973 0.52593381 0.55970818 0.18346685]]
[[0.80697049 0.41708931 0.95380595 0.51481069]
 [0.86411461 0.40260986 1.0996552  0.51796802]]
